### ISSUE TITLE
Item Info Stops Displaying

### ISSUE THREAD

**Issue by VRNocturne** [Rycona/FF6-BC-Scouter#1]
Sometimes (often when returning to the world map) the scouter window will stop showing information in the Item menu, but it will display for item drops and shop sell menus.

For it to show info in the item window again, I have to close and restart the script. And it will work until the issue arises again.

I'm using Bizhawk 2.6 and the latest BC EX 4 version.

**Comment by Rycona** [comment]
Thanks for reporting and apologies for the inconvenience of having to restart the script. Hopefully, I will have a fix soon.

**Comment by Rycona** [comment]
Improved primary program state detection should prevent RAM being read inappropriately. That should fix this issue.
