### ISSUE TITLE
Command Changer Info

### ISSUE THREAD

**Issue by VRNocturne** [Rycona/FF6-BC-Scouter#2]
Command changer items display the vanilla command change except in the Relic Equip menu. If viewed in the item menu, it shows the vanilla command change for that item, not the one that is in the seed.

**Comment by Rycona** [comment]
Thanks for reporting and apologies for any inconvenience. This is something that was happening before and I thought I had fixed it, but alas...

Hopefully, I will have a fix soon.

**Comment by Rycona** [comment]
Made a flag to pull the command change names when first called.
